// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJB3alaZ-ZwzoJQcubpZIR6pFz6I9Jn9o',
    appId: '1:581610296622:web:6602d87bd8eb5c7af6d6bf',
    messagingSenderId: '581610296622',
    projectId: 'flutter-firebase-1-1a3a3',
    authDomain: 'flutter-firebase-1-1a3a3.firebaseapp.com',
    storageBucket: 'flutter-firebase-1-1a3a3.firebasestorage.app',
    measurementId: 'G-QGYZ9TCYFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHHb9bfBCpCmAOhwH0dh7GqJTp2-wPss',
    appId: '1:581610296622:android:75bc4f85b2a05477f6d6bf',
    messagingSenderId: '581610296622',
    projectId: 'flutter-firebase-1-1a3a3',
    storageBucket: 'flutter-firebase-1-1a3a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJqbPP1NcX_12IOhnvia4clGOmomuR3tM',
    appId: '1:581610296622:ios:339c7908120f86baf6d6bf',
    messagingSenderId: '581610296622',
    projectId: 'flutter-firebase-1-1a3a3',
    storageBucket: 'flutter-firebase-1-1a3a3.firebasestorage.app',
    iosBundleId: 'com.example.firebasetestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJqbPP1NcX_12IOhnvia4clGOmomuR3tM',
    appId: '1:581610296622:ios:339c7908120f86baf6d6bf',
    messagingSenderId: '581610296622',
    projectId: 'flutter-firebase-1-1a3a3',
    storageBucket: 'flutter-firebase-1-1a3a3.firebasestorage.app',
    iosBundleId: 'com.example.firebasetestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJB3alaZ-ZwzoJQcubpZIR6pFz6I9Jn9o',
    appId: '1:581610296622:web:77aa919f9c4445a3f6d6bf',
    messagingSenderId: '581610296622',
    projectId: 'flutter-firebase-1-1a3a3',
    authDomain: 'flutter-firebase-1-1a3a3.firebaseapp.com',
    storageBucket: 'flutter-firebase-1-1a3a3.firebasestorage.app',
    measurementId: 'G-CZSHVSWEJ9',
  );
}
